<!-- Required Js -->
<script src="{{ asset('assets/js/vendor-all.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/menu-setting.min.js') }}"></script>
<script src="{{ asset('assets/js/pcoded.min.js') }}"></script>
<!-- amchart js -->
<script src="{{ asset('assets/plugins/amchart/js/amcharts.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/gauge.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/serial.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/light.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/pie.min.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/ammap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/usaLow.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/radar.js') }}"></script>
<script src="{{ asset('assets/plugins/amchart/js/worldLow.js') }}"></script>
<!-- notification Js -->
<script src="{{ asset('assets/plugins/notification/js/bootstrap-growl.min.js') }}"></script>

<!-- dashboard-custom js -->
<script src="{{ asset('assets/js/pages/dashboard-custom.js') }}"></script>